/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.Bookings;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingsRecord extends UpdatableRecordImpl<BookingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bookings.id</code>.
     */
    public BookingsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bookings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bookings.route_id</code>.
     */
    public BookingsRecord setRouteId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bookings.route_id</code>.
     */
    public Integer getRouteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.bookings.user_id</code>.
     */
    public BookingsRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bookings.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.bookings.created_at</code>.
     */
    public BookingsRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.bookings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.bookings.status</code>.
     */
    public BookingsRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.bookings.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingsRecord
     */
    public BookingsRecord() {
        super(Bookings.BOOKINGS);
    }

    /**
     * Create a detached, initialised BookingsRecord
     */
    public BookingsRecord(Integer id, Integer routeId, Integer userId, LocalDateTime createdAt, String status) {
        super(Bookings.BOOKINGS);

        setId(id);
        setRouteId(routeId);
        setUserId(userId);
        setCreatedAt(createdAt);
        setStatus(status);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised BookingsRecord
     */
    public BookingsRecord(com.example.transport_marketplace.jooq.tables.pojos.Bookings value) {
        super(Bookings.BOOKINGS);

        if (value != null) {
            setId(value.getId());
            setRouteId(value.getRouteId());
            setUserId(value.getUserId());
            setCreatedAt(value.getCreatedAt());
            setStatus(value.getStatus());
            resetTouchedOnNotNull();
        }
    }
}
