/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.Devices;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DevicesRecord extends UpdatableRecordImpl<DevicesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.devices.id</code>.
     */
    public DevicesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.devices.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.devices.user_id</code>.
     */
    public DevicesRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.devices.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.devices.device_fingerprint</code>.
     */
    public DevicesRecord setDeviceFingerprint(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.devices.device_fingerprint</code>.
     */
    public String getDeviceFingerprint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.devices.user_agent</code>.
     */
    public DevicesRecord setUserAgent(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.devices.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicesRecord
     */
    public DevicesRecord() {
        super(Devices.DEVICES);
    }

    /**
     * Create a detached, initialised DevicesRecord
     */
    public DevicesRecord(Integer id, Integer userId, String deviceFingerprint, String userAgent) {
        super(Devices.DEVICES);

        setId(id);
        setUserId(userId);
        setDeviceFingerprint(deviceFingerprint);
        setUserAgent(userAgent);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DevicesRecord
     */
    public DevicesRecord(com.example.transport_marketplace.jooq.tables.pojos.Devices value) {
        super(Devices.DEVICES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setDeviceFingerprint(value.getDeviceFingerprint());
            setUserAgent(value.getUserAgent());
            resetTouchedOnNotNull();
        }
    }
}
