/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.Payments;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentsRecord extends UpdatableRecordImpl<PaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.payments.amount</code>.
     */
    public PaymentsRecord setAmount(Double value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.payments.booking_id</code>.
     */
    public PaymentsRecord setBookingId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.booking_id</code>.
     */
    public Integer getBookingId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.payments.id</code>.
     */
    public PaymentsRecord setId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.payments.user_id</code>.
     */
    public PaymentsRecord setUserId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.payments.code_expires_at</code>.
     */
    public PaymentsRecord setCodeExpiresAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.code_expires_at</code>.
     */
    public LocalDateTime getCodeExpiresAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.payments.created_at</code>.
     */
    public PaymentsRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.payments.external_id</code>.
     */
    public PaymentsRecord setExternalId(UUID value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.external_id</code>.
     */
    public UUID getExternalId() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.payments.confirmation_code</code>.
     */
    public PaymentsRecord setConfirmationCode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.confirmation_code</code>.
     */
    public String getConfirmationCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.payments.description</code>.
     */
    public PaymentsRecord setDescription(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.payments.payment_method</code>.
     */
    public PaymentsRecord setPaymentMethod(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.payment_method</code>.
     */
    public String getPaymentMethod() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.payments.payment_status</code>.
     */
    public PaymentsRecord setPaymentStatus(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.payments.payment_status</code>.
     */
    public String getPaymentStatus() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentsRecord
     */
    public PaymentsRecord() {
        super(Payments.PAYMENTS);
    }

    /**
     * Create a detached, initialised PaymentsRecord
     */
    public PaymentsRecord(Double amount, Integer bookingId, Integer id, Integer userId, LocalDateTime codeExpiresAt, LocalDateTime createdAt, UUID externalId, String confirmationCode, String description, String paymentMethod, String paymentStatus) {
        super(Payments.PAYMENTS);

        setAmount(amount);
        setBookingId(bookingId);
        setId(id);
        setUserId(userId);
        setCodeExpiresAt(codeExpiresAt);
        setCreatedAt(createdAt);
        setExternalId(externalId);
        setConfirmationCode(confirmationCode);
        setDescription(description);
        setPaymentMethod(paymentMethod);
        setPaymentStatus(paymentStatus);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PaymentsRecord
     */
    public PaymentsRecord(com.example.transport_marketplace.jooq.tables.pojos.Payments value) {
        super(Payments.PAYMENTS);

        if (value != null) {
            setAmount(value.getAmount());
            setBookingId(value.getBookingId());
            setId(value.getId());
            setUserId(value.getUserId());
            setCodeExpiresAt(value.getCodeExpiresAt());
            setCreatedAt(value.getCreatedAt());
            setExternalId(value.getExternalId());
            setConfirmationCode(value.getConfirmationCode());
            setDescription(value.getDescription());
            setPaymentMethod(value.getPaymentMethod());
            setPaymentStatus(value.getPaymentStatus());
            resetTouchedOnNotNull();
        }
    }
}
