/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.RefreshTokens;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokensRecord extends UpdatableRecordImpl<RefreshTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_tokens.device_id</code>.
     */
    public RefreshTokensRecord setDeviceId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.device_id</code>.
     */
    public Integer getDeviceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.refresh_tokens.id</code>.
     */
    public RefreshTokensRecord setId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.refresh_tokens.user_id</code>.
     */
    public RefreshTokensRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public RefreshTokensRecord setExpiryDate(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public OffsetDateTime getExpiryDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.refresh_tokens.token</code>.
     */
    public RefreshTokensRecord setToken(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.refresh_tokens.token</code>.
     */
    public String getToken() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokensRecord
     */
    public RefreshTokensRecord() {
        super(RefreshTokens.REFRESH_TOKENS);
    }

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    public RefreshTokensRecord(Integer deviceId, Integer id, Integer userId, OffsetDateTime expiryDate, String token) {
        super(RefreshTokens.REFRESH_TOKENS);

        setDeviceId(deviceId);
        setId(id);
        setUserId(userId);
        setExpiryDate(expiryDate);
        setToken(token);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshTokensRecord
     */
    public RefreshTokensRecord(com.example.transport_marketplace.jooq.tables.pojos.RefreshTokens value) {
        super(RefreshTokens.REFRESH_TOKENS);

        if (value != null) {
            setDeviceId(value.getDeviceId());
            setId(value.getId());
            setUserId(value.getUserId());
            setExpiryDate(value.getExpiryDate());
            setToken(value.getToken());
            resetTouchedOnNotNull();
        }
    }
}
