/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.Routes;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoutesRecord extends UpdatableRecordImpl<RoutesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.routes.available_seats</code>.
     */
    public RoutesRecord setAvailableSeats(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.available_seats</code>.
     */
    public Integer getAvailableSeats() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.routes.id</code>.
     */
    public RoutesRecord setId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.routes.price</code>.
     */
    public RoutesRecord setPrice(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.routes.arrival_time</code>.
     */
    public RoutesRecord setArrivalTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.arrival_time</code>.
     */
    public LocalDateTime getArrivalTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.routes.destination_time</code>.
     */
    public RoutesRecord setDestinationTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.destination_time</code>.
     */
    public LocalDateTime getDestinationTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.routes.route_from</code>.
     */
    public RoutesRecord setRouteFrom(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.route_from</code>.
     */
    public String getRouteFrom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.routes.route_to</code>.
     */
    public RoutesRecord setRouteTo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.route_to</code>.
     */
    public String getRouteTo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.routes.transport</code>.
     */
    public RoutesRecord setTransport(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.routes.transport</code>.
     */
    public String getTransport() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutesRecord
     */
    public RoutesRecord() {
        super(Routes.ROUTES);
    }

    /**
     * Create a detached, initialised RoutesRecord
     */
    public RoutesRecord(Integer availableSeats, Integer id, Double price, LocalDateTime arrivalTime, LocalDateTime destinationTime, String routeFrom, String routeTo, String transport) {
        super(Routes.ROUTES);

        setAvailableSeats(availableSeats);
        setId(id);
        setPrice(price);
        setArrivalTime(arrivalTime);
        setDestinationTime(destinationTime);
        setRouteFrom(routeFrom);
        setRouteTo(routeTo);
        setTransport(transport);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RoutesRecord
     */
    public RoutesRecord(com.example.transport_marketplace.jooq.tables.pojos.Routes value) {
        super(Routes.ROUTES);

        if (value != null) {
            setAvailableSeats(value.getAvailableSeats());
            setId(value.getId());
            setPrice(value.getPrice());
            setArrivalTime(value.getArrivalTime());
            setDestinationTime(value.getDestinationTime());
            setRouteFrom(value.getRouteFrom());
            setRouteTo(value.getRouteTo());
            setTransport(value.getTransport());
            resetTouchedOnNotNull();
        }
    }
}
