/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.records;


import com.example.transport_marketplace.jooq.tables.Users;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.balance</code>.
     */
    public UsersRecord setBalance(Double value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    public UsersRecord setId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public UsersRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.role</code>.
     */
    public UsersRecord setRole(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.role</code>.
     */
    public String getRole() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public UsersRecord setUsername(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    public String getUsername() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Double balance, Integer id, String email, String password, String role, String username) {
        super(Users.USERS);

        setBalance(balance);
        setId(id);
        setEmail(email);
        setPassword(password);
        setRole(role);
        setUsername(username);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(com.example.transport_marketplace.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setBalance(value.getBalance());
            setId(value.getId());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setRole(value.getRole());
            setUsername(value.getUsername());
            resetTouchedOnNotNull();
        }
    }
}
