/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Bookings implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer routeId;
    private final Integer userId;
    private final LocalDateTime createdAt;
    private final String status;

    public Bookings(Bookings value) {
        this.id = value.id;
        this.routeId = value.routeId;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.status = value.status;
    }

    public Bookings(
        Integer id,
        Integer routeId,
        Integer userId,
        LocalDateTime createdAt,
        String status
    ) {
        this.id = id;
        this.routeId = routeId;
        this.userId = userId;
        this.createdAt = createdAt;
        this.status = status;
    }

    /**
     * Getter for <code>public.bookings.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.bookings.route_id</code>.
     */
    public Integer getRouteId() {
        return this.routeId;
    }

    /**
     * Getter for <code>public.bookings.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.bookings.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.bookings.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Bookings other = (Bookings) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.routeId == null) {
            if (other.routeId != null)
                return false;
        }
        else if (!this.routeId.equals(other.routeId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.routeId == null) ? 0 : this.routeId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bookings (");

        sb.append(id);
        sb.append(", ").append(routeId);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
