/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Devices implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer userId;
    private final String deviceFingerprint;
    private final String userAgent;

    public Devices(Devices value) {
        this.id = value.id;
        this.userId = value.userId;
        this.deviceFingerprint = value.deviceFingerprint;
        this.userAgent = value.userAgent;
    }

    public Devices(
        Integer id,
        Integer userId,
        String deviceFingerprint,
        String userAgent
    ) {
        this.id = id;
        this.userId = userId;
        this.deviceFingerprint = deviceFingerprint;
        this.userAgent = userAgent;
    }

    /**
     * Getter for <code>public.devices.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.devices.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.devices.device_fingerprint</code>.
     */
    public String getDeviceFingerprint() {
        return this.deviceFingerprint;
    }

    /**
     * Getter for <code>public.devices.user_agent</code>.
     */
    public String getUserAgent() {
        return this.userAgent;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Devices other = (Devices) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.deviceFingerprint == null) {
            if (other.deviceFingerprint != null)
                return false;
        }
        else if (!this.deviceFingerprint.equals(other.deviceFingerprint))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.deviceFingerprint == null) ? 0 : this.deviceFingerprint.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Devices (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(deviceFingerprint);
        sb.append(", ").append(userAgent);

        sb.append(")");
        return sb.toString();
    }
}
