/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payments implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Double amount;
    private final Integer bookingId;
    private final Integer id;
    private final Integer userId;
    private final LocalDateTime codeExpiresAt;
    private final LocalDateTime createdAt;
    private final UUID externalId;
    private final String confirmationCode;
    private final String description;
    private final String paymentMethod;
    private final String paymentStatus;

    public Payments(Payments value) {
        this.amount = value.amount;
        this.bookingId = value.bookingId;
        this.id = value.id;
        this.userId = value.userId;
        this.codeExpiresAt = value.codeExpiresAt;
        this.createdAt = value.createdAt;
        this.externalId = value.externalId;
        this.confirmationCode = value.confirmationCode;
        this.description = value.description;
        this.paymentMethod = value.paymentMethod;
        this.paymentStatus = value.paymentStatus;
    }

    public Payments(
        Double amount,
        Integer bookingId,
        Integer id,
        Integer userId,
        LocalDateTime codeExpiresAt,
        LocalDateTime createdAt,
        UUID externalId,
        String confirmationCode,
        String description,
        String paymentMethod,
        String paymentStatus
    ) {
        this.amount = amount;
        this.bookingId = bookingId;
        this.id = id;
        this.userId = userId;
        this.codeExpiresAt = codeExpiresAt;
        this.createdAt = createdAt;
        this.externalId = externalId;
        this.confirmationCode = confirmationCode;
        this.description = description;
        this.paymentMethod = paymentMethod;
        this.paymentStatus = paymentStatus;
    }

    /**
     * Getter for <code>public.payments.amount</code>.
     */
    public Double getAmount() {
        return this.amount;
    }

    /**
     * Getter for <code>public.payments.booking_id</code>.
     */
    public Integer getBookingId() {
        return this.bookingId;
    }

    /**
     * Getter for <code>public.payments.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.payments.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.payments.code_expires_at</code>.
     */
    public LocalDateTime getCodeExpiresAt() {
        return this.codeExpiresAt;
    }

    /**
     * Getter for <code>public.payments.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.payments.external_id</code>.
     */
    public UUID getExternalId() {
        return this.externalId;
    }

    /**
     * Getter for <code>public.payments.confirmation_code</code>.
     */
    public String getConfirmationCode() {
        return this.confirmationCode;
    }

    /**
     * Getter for <code>public.payments.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.payments.payment_method</code>.
     */
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    /**
     * Getter for <code>public.payments.payment_status</code>.
     */
    public String getPaymentStatus() {
        return this.paymentStatus;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Payments other = (Payments) obj;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.bookingId == null) {
            if (other.bookingId != null)
                return false;
        }
        else if (!this.bookingId.equals(other.bookingId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.codeExpiresAt == null) {
            if (other.codeExpiresAt != null)
                return false;
        }
        else if (!this.codeExpiresAt.equals(other.codeExpiresAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.confirmationCode == null) {
            if (other.confirmationCode != null)
                return false;
        }
        else if (!this.confirmationCode.equals(other.confirmationCode))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.paymentMethod == null) {
            if (other.paymentMethod != null)
                return false;
        }
        else if (!this.paymentMethod.equals(other.paymentMethod))
            return false;
        if (this.paymentStatus == null) {
            if (other.paymentStatus != null)
                return false;
        }
        else if (!this.paymentStatus.equals(other.paymentStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.bookingId == null) ? 0 : this.bookingId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.codeExpiresAt == null) ? 0 : this.codeExpiresAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.confirmationCode == null) ? 0 : this.confirmationCode.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.paymentMethod == null) ? 0 : this.paymentMethod.hashCode());
        result = prime * result + ((this.paymentStatus == null) ? 0 : this.paymentStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payments (");

        sb.append(amount);
        sb.append(", ").append(bookingId);
        sb.append(", ").append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(codeExpiresAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(externalId);
        sb.append(", ").append(confirmationCode);
        sb.append(", ").append(description);
        sb.append(", ").append(paymentMethod);
        sb.append(", ").append(paymentStatus);

        sb.append(")");
        return sb.toString();
    }
}
