/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokens implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer deviceId;
    private final Integer id;
    private final Integer userId;
    private final OffsetDateTime expiryDate;
    private final String token;

    public RefreshTokens(RefreshTokens value) {
        this.deviceId = value.deviceId;
        this.id = value.id;
        this.userId = value.userId;
        this.expiryDate = value.expiryDate;
        this.token = value.token;
    }

    public RefreshTokens(
        Integer deviceId,
        Integer id,
        Integer userId,
        OffsetDateTime expiryDate,
        String token
    ) {
        this.deviceId = deviceId;
        this.id = id;
        this.userId = userId;
        this.expiryDate = expiryDate;
        this.token = token;
    }

    /**
     * Getter for <code>public.refresh_tokens.device_id</code>.
     */
    public Integer getDeviceId() {
        return this.deviceId;
    }

    /**
     * Getter for <code>public.refresh_tokens.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.refresh_tokens.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.refresh_tokens.expiry_date</code>.
     */
    public OffsetDateTime getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Getter for <code>public.refresh_tokens.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshTokens other = (RefreshTokens) obj;
        if (this.deviceId == null) {
            if (other.deviceId != null)
                return false;
        }
        else if (!this.deviceId.equals(other.deviceId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.expiryDate == null) {
            if (other.expiryDate != null)
                return false;
        }
        else if (!this.expiryDate.equals(other.expiryDate))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.deviceId == null) ? 0 : this.deviceId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.expiryDate == null) ? 0 : this.expiryDate.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshTokens (");

        sb.append(deviceId);
        sb.append(", ").append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(expiryDate);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
