/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer availableSeats;
    private final Integer id;
    private final Double price;
    private final LocalDateTime arrivalTime;
    private final LocalDateTime destinationTime;
    private final String routeFrom;
    private final String routeTo;
    private final String transport;

    public Routes(Routes value) {
        this.availableSeats = value.availableSeats;
        this.id = value.id;
        this.price = value.price;
        this.arrivalTime = value.arrivalTime;
        this.destinationTime = value.destinationTime;
        this.routeFrom = value.routeFrom;
        this.routeTo = value.routeTo;
        this.transport = value.transport;
    }

    public Routes(
        Integer availableSeats,
        Integer id,
        Double price,
        LocalDateTime arrivalTime,
        LocalDateTime destinationTime,
        String routeFrom,
        String routeTo,
        String transport
    ) {
        this.availableSeats = availableSeats;
        this.id = id;
        this.price = price;
        this.arrivalTime = arrivalTime;
        this.destinationTime = destinationTime;
        this.routeFrom = routeFrom;
        this.routeTo = routeTo;
        this.transport = transport;
    }

    /**
     * Getter for <code>public.routes.available_seats</code>.
     */
    public Integer getAvailableSeats() {
        return this.availableSeats;
    }

    /**
     * Getter for <code>public.routes.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.routes.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>public.routes.arrival_time</code>.
     */
    public LocalDateTime getArrivalTime() {
        return this.arrivalTime;
    }

    /**
     * Getter for <code>public.routes.destination_time</code>.
     */
    public LocalDateTime getDestinationTime() {
        return this.destinationTime;
    }

    /**
     * Getter for <code>public.routes.route_from</code>.
     */
    public String getRouteFrom() {
        return this.routeFrom;
    }

    /**
     * Getter for <code>public.routes.route_to</code>.
     */
    public String getRouteTo() {
        return this.routeTo;
    }

    /**
     * Getter for <code>public.routes.transport</code>.
     */
    public String getTransport() {
        return this.transport;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Routes other = (Routes) obj;
        if (this.availableSeats == null) {
            if (other.availableSeats != null)
                return false;
        }
        else if (!this.availableSeats.equals(other.availableSeats))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.arrivalTime == null) {
            if (other.arrivalTime != null)
                return false;
        }
        else if (!this.arrivalTime.equals(other.arrivalTime))
            return false;
        if (this.destinationTime == null) {
            if (other.destinationTime != null)
                return false;
        }
        else if (!this.destinationTime.equals(other.destinationTime))
            return false;
        if (this.routeFrom == null) {
            if (other.routeFrom != null)
                return false;
        }
        else if (!this.routeFrom.equals(other.routeFrom))
            return false;
        if (this.routeTo == null) {
            if (other.routeTo != null)
                return false;
        }
        else if (!this.routeTo.equals(other.routeTo))
            return false;
        if (this.transport == null) {
            if (other.transport != null)
                return false;
        }
        else if (!this.transport.equals(other.transport))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.availableSeats == null) ? 0 : this.availableSeats.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.arrivalTime == null) ? 0 : this.arrivalTime.hashCode());
        result = prime * result + ((this.destinationTime == null) ? 0 : this.destinationTime.hashCode());
        result = prime * result + ((this.routeFrom == null) ? 0 : this.routeFrom.hashCode());
        result = prime * result + ((this.routeTo == null) ? 0 : this.routeTo.hashCode());
        result = prime * result + ((this.transport == null) ? 0 : this.transport.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Routes (");

        sb.append(availableSeats);
        sb.append(", ").append(id);
        sb.append(", ").append(price);
        sb.append(", ").append(arrivalTime);
        sb.append(", ").append(destinationTime);
        sb.append(", ").append(routeFrom);
        sb.append(", ").append(routeTo);
        sb.append(", ").append(transport);

        sb.append(")");
        return sb.toString();
    }
}
