/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables;


import com.example.transport_marketplace.jooq.Keys;
import com.example.transport_marketplace.jooq.Public;
import com.example.transport_marketplace.jooq.tables.RefreshTokens.RefreshTokensPath;
import com.example.transport_marketplace.jooq.tables.Users.UsersPath;
import com.example.transport_marketplace.jooq.tables.records.DevicesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Devices extends TableImpl<DevicesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.devices</code>
     */
    public static final Devices DEVICES = new Devices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicesRecord> getRecordType() {
        return DevicesRecord.class;
    }

    /**
     * The column <code>public.devices.id</code>.
     */
    public final TableField<DevicesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.devices.user_id</code>.
     */
    public final TableField<DevicesRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.devices.device_fingerprint</code>.
     */
    public final TableField<DevicesRecord, String> DEVICE_FINGERPRINT = createField(DSL.name("device_fingerprint"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.devices.user_agent</code>.
     */
    public final TableField<DevicesRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(255), this, "");

    private Devices(Name alias, Table<DevicesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Devices(Name alias, Table<DevicesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.devices</code> table reference
     */
    public Devices(String alias) {
        this(DSL.name(alias), DEVICES);
    }

    /**
     * Create an aliased <code>public.devices</code> table reference
     */
    public Devices(Name alias) {
        this(alias, DEVICES);
    }

    /**
     * Create a <code>public.devices</code> table reference
     */
    public Devices() {
        this(DSL.name("devices"), null);
    }

    public <O extends Record> Devices(Table<O> path, ForeignKey<O, DevicesRecord> childPath, InverseForeignKey<O, DevicesRecord> parentPath) {
        super(path, childPath, parentPath, DEVICES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.20.9"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class DevicesPath extends Devices implements Path<DevicesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DevicesPath(Table<O> path, ForeignKey<O, DevicesRecord> childPath, InverseForeignKey<O, DevicesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DevicesPath(Name alias, Table<DevicesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DevicesPath as(String alias) {
            return new DevicesPath(DSL.name(alias), this);
        }

        @Override
        public DevicesPath as(Name alias) {
            return new DevicesPath(alias, this);
        }

        @Override
        public DevicesPath as(Table<?> alias) {
            return new DevicesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DevicesRecord, Integer> getIdentity() {
        return (Identity<DevicesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DevicesRecord> getPrimaryKey() {
        return Keys.DEVICES_PKEY;
    }

    @Override
    public List<UniqueKey<DevicesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_DEVICE_USER);
    }

    @Override
    public List<ForeignKey<DevicesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEVICES__FKRFBRI1YMRWYWDYDC4DGYWE1BT);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.DEVICES__FKRFBRI1YMRWYWDYDC4DGYWE1BT, null);

        return _users;
    }

    private transient RefreshTokensPath _refreshTokens;

    /**
     * Get the implicit to-many join path to the
     * <code>public.refresh_tokens</code> table
     */
    public RefreshTokensPath refreshTokens() {
        if (_refreshTokens == null)
            _refreshTokens = new RefreshTokensPath(this, null, Keys.REFRESH_TOKENS__FKA3BXDJ3AQ8Y05GPIDWQAHRX97.getInverseKey());

        return _refreshTokens;
    }

    @Override
    public Devices as(String alias) {
        return new Devices(DSL.name(alias), this);
    }

    @Override
    public Devices as(Name alias) {
        return new Devices(alias, this);
    }

    @Override
    public Devices as(Table<?> alias) {
        return new Devices(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devices rename(String name) {
        return new Devices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devices rename(Name name) {
        return new Devices(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devices rename(Table<?> name) {
        return new Devices(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices where(Condition condition) {
        return new Devices(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Devices where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Devices where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Devices where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Devices where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Devices whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
