/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables;


import com.example.transport_marketplace.jooq.Keys;
import com.example.transport_marketplace.jooq.Public;
import com.example.transport_marketplace.jooq.tables.Bookings.BookingsPath;
import com.example.transport_marketplace.jooq.tables.Users.UsersPath;
import com.example.transport_marketplace.jooq.tables.records.PaymentsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Payments extends TableImpl<PaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.payments</code>
     */
    public static final Payments PAYMENTS = new Payments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentsRecord> getRecordType() {
        return PaymentsRecord.class;
    }

    /**
     * The column <code>public.payments.amount</code>.
     */
    public final TableField<PaymentsRecord, Double> AMOUNT = createField(DSL.name("amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.payments.booking_id</code>.
     */
    public final TableField<PaymentsRecord, Integer> BOOKING_ID = createField(DSL.name("booking_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.payments.id</code>.
     */
    public final TableField<PaymentsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.payments.user_id</code>.
     */
    public final TableField<PaymentsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.payments.code_expires_at</code>.
     */
    public final TableField<PaymentsRecord, LocalDateTime> CODE_EXPIRES_AT = createField(DSL.name("code_expires_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.payments.created_at</code>.
     */
    public final TableField<PaymentsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.payments.external_id</code>.
     */
    public final TableField<PaymentsRecord, UUID> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.payments.confirmation_code</code>.
     */
    public final TableField<PaymentsRecord, String> CONFIRMATION_CODE = createField(DSL.name("confirmation_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.payments.description</code>.
     */
    public final TableField<PaymentsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.payments.payment_method</code>.
     */
    public final TableField<PaymentsRecord, String> PAYMENT_METHOD = createField(DSL.name("payment_method"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.payments.payment_status</code>.
     */
    public final TableField<PaymentsRecord, String> PAYMENT_STATUS = createField(DSL.name("payment_status"), SQLDataType.VARCHAR(255), this, "");

    private Payments(Name alias, Table<PaymentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Payments(Name alias, Table<PaymentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    public Payments(String alias) {
        this(DSL.name(alias), PAYMENTS);
    }

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    public Payments(Name alias) {
        this(alias, PAYMENTS);
    }

    /**
     * Create a <code>public.payments</code> table reference
     */
    public Payments() {
        this(DSL.name("payments"), null);
    }

    public <O extends Record> Payments(Table<O> path, ForeignKey<O, PaymentsRecord> childPath, InverseForeignKey<O, PaymentsRecord> parentPath) {
        super(path, childPath, parentPath, PAYMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.20.9"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PaymentsPath extends Payments implements Path<PaymentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PaymentsPath(Table<O> path, ForeignKey<O, PaymentsRecord> childPath, InverseForeignKey<O, PaymentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PaymentsPath(Name alias, Table<PaymentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PaymentsPath as(String alias) {
            return new PaymentsPath(DSL.name(alias), this);
        }

        @Override
        public PaymentsPath as(Name alias) {
            return new PaymentsPath(alias, this);
        }

        @Override
        public PaymentsPath as(Table<?> alias) {
            return new PaymentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PaymentsRecord, Integer> getIdentity() {
        return (Identity<PaymentsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PaymentsRecord> getPrimaryKey() {
        return Keys.PAYMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<PaymentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PAYMENTS__FKC52O2B1JKXTTNGUFQP3T7JR3H, Keys.PAYMENTS__FKJ94HGY9V5FW1MUNB90TAR2EJE);
    }

    private transient BookingsPath _bookings;

    /**
     * Get the implicit join path to the <code>public.bookings</code> table.
     */
    public BookingsPath bookings() {
        if (_bookings == null)
            _bookings = new BookingsPath(this, Keys.PAYMENTS__FKC52O2B1JKXTTNGUFQP3T7JR3H, null);

        return _bookings;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.PAYMENTS__FKJ94HGY9V5FW1MUNB90TAR2EJE, null);

        return _users;
    }

    @Override
    public List<Check<PaymentsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("payments_payment_method_check"), "(((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'BANK_TRANSFER'::character varying, 'ELECTRONIC'::character varying, 'SIMULATION'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("payments_payment_status_check"), "(((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])))", true)
        );
    }

    @Override
    public Payments as(String alias) {
        return new Payments(DSL.name(alias), this);
    }

    @Override
    public Payments as(Name alias) {
        return new Payments(alias, this);
    }

    @Override
    public Payments as(Table<?> alias) {
        return new Payments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(String name) {
        return new Payments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Name name) {
        return new Payments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Table<?> name) {
        return new Payments(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Condition condition) {
        return new Payments(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Payments where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Payments whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
