/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq.tables;


import com.example.transport_marketplace.jooq.Keys;
import com.example.transport_marketplace.jooq.Public;
import com.example.transport_marketplace.jooq.tables.Devices.DevicesPath;
import com.example.transport_marketplace.jooq.tables.Users.UsersPath;
import com.example.transport_marketplace.jooq.tables.records.RefreshTokensRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokens extends TableImpl<RefreshTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.refresh_tokens</code>
     */
    public static final RefreshTokens REFRESH_TOKENS = new RefreshTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RefreshTokensRecord> getRecordType() {
        return RefreshTokensRecord.class;
    }

    /**
     * The column <code>public.refresh_tokens.device_id</code>.
     */
    public final TableField<RefreshTokensRecord, Integer> DEVICE_ID = createField(DSL.name("device_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.refresh_tokens.id</code>.
     */
    public final TableField<RefreshTokensRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.refresh_tokens.user_id</code>.
     */
    public final TableField<RefreshTokensRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.refresh_tokens.expiry_date</code>.
     */
    public final TableField<RefreshTokensRecord, OffsetDateTime> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.refresh_tokens.token</code>.
     */
    public final TableField<RefreshTokensRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private RefreshTokens(Name alias, Table<RefreshTokensRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RefreshTokens(Name alias, Table<RefreshTokensRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens(String alias) {
        this(DSL.name(alias), REFRESH_TOKENS);
    }

    /**
     * Create an aliased <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens(Name alias) {
        this(alias, REFRESH_TOKENS);
    }

    /**
     * Create a <code>public.refresh_tokens</code> table reference
     */
    public RefreshTokens() {
        this(DSL.name("refresh_tokens"), null);
    }

    public <O extends Record> RefreshTokens(Table<O> path, ForeignKey<O, RefreshTokensRecord> childPath, InverseForeignKey<O, RefreshTokensRecord> parentPath) {
        super(path, childPath, parentPath, REFRESH_TOKENS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.20.9"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class RefreshTokensPath extends RefreshTokens implements Path<RefreshTokensRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RefreshTokensPath(Table<O> path, ForeignKey<O, RefreshTokensRecord> childPath, InverseForeignKey<O, RefreshTokensRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RefreshTokensPath(Name alias, Table<RefreshTokensRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RefreshTokensPath as(String alias) {
            return new RefreshTokensPath(DSL.name(alias), this);
        }

        @Override
        public RefreshTokensPath as(Name alias) {
            return new RefreshTokensPath(alias, this);
        }

        @Override
        public RefreshTokensPath as(Table<?> alias) {
            return new RefreshTokensPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RefreshTokensRecord, Integer> getIdentity() {
        return (Identity<RefreshTokensRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RefreshTokensRecord> getPrimaryKey() {
        return Keys.REFRESH_TOKENS_PKEY;
    }

    @Override
    public List<UniqueKey<RefreshTokensRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REFRESH_TOKENS_TOKEN_KEY, Keys.UK_USER_DEVICE);
    }

    @Override
    public List<ForeignKey<RefreshTokensRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REFRESH_TOKENS__FK1LIH5Y2NPSF8U5O3VHDB9Y0OS, Keys.REFRESH_TOKENS__FKA3BXDJ3AQ8Y05GPIDWQAHRX97);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.REFRESH_TOKENS__FK1LIH5Y2NPSF8U5O3VHDB9Y0OS, null);

        return _users;
    }

    private transient DevicesPath _devices;

    /**
     * Get the implicit join path to the <code>public.devices</code> table.
     */
    public DevicesPath devices() {
        if (_devices == null)
            _devices = new DevicesPath(this, Keys.REFRESH_TOKENS__FKA3BXDJ3AQ8Y05GPIDWQAHRX97, null);

        return _devices;
    }

    @Override
    public RefreshTokens as(String alias) {
        return new RefreshTokens(DSL.name(alias), this);
    }

    @Override
    public RefreshTokens as(Name alias) {
        return new RefreshTokens(alias, this);
    }

    @Override
    public RefreshTokens as(Table<?> alias) {
        return new RefreshTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(String name) {
        return new RefreshTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(Name name) {
        return new RefreshTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RefreshTokens rename(Table<?> name) {
        return new RefreshTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Condition condition) {
        return new RefreshTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RefreshTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RefreshTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
