CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NULL,
    balance DOUBLE PRECISION DEFAULT 0,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE routes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_from VARCHAR(255) NOT NULL,
    route_to VARCHAR(255) NOT NULL,
    transport VARCHAR(50) NOT NULL,
    destination_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    available_seats INTEGER,
    price DOUBLE PRECISION DEFAULT 0
);

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_fingerprint VARCHAR(255) NOT NULL,
    user_agent VARCHAR(140) NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_device_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT uk_device_user UNIQUE(device_fingerprint, user_id)
);

CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_route
        FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID NOT NULL UNIQUE,
    amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    description TEXT,
    confirmation_code VARCHAR(7),
    code_expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    booking_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);