CREATE TABLE refresh_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    user_id INTEGER NOT NULL,
    device_id INTEGER NOT NULL,

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_token_device
        FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_device UNIQUE(user_id, device_id)
);