/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq;


import com.example.transport_marketplace.jooq.tables.Bookings;
import com.example.transport_marketplace.jooq.tables.Devices;
import com.example.transport_marketplace.jooq.tables.Payments;
import com.example.transport_marketplace.jooq.tables.RefreshTokens;
import com.example.transport_marketplace.jooq.tables.Routes;
import com.example.transport_marketplace.jooq.tables.Users;
import com.example.transport_marketplace.jooq.tables.records.BookingsRecord;
import com.example.transport_marketplace.jooq.tables.records.DevicesRecord;
import com.example.transport_marketplace.jooq.tables.records.PaymentsRecord;
import com.example.transport_marketplace.jooq.tables.records.RefreshTokensRecord;
import com.example.transport_marketplace.jooq.tables.records.RoutesRecord;
import com.example.transport_marketplace.jooq.tables.records.UsersRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookingsRecord> BOOKINGS_PKEY = Internal.createUniqueKey(Bookings.BOOKINGS, DSL.name("bookings_pkey"), new TableField[] { Bookings.BOOKINGS.ID }, true);
    public static final UniqueKey<DevicesRecord> DEVICES_PKEY = Internal.createUniqueKey(Devices.DEVICES, DSL.name("devices_pkey"), new TableField[] { Devices.DEVICES.ID }, true);
    public static final UniqueKey<DevicesRecord> UK_DEVICE_USER = Internal.createUniqueKey(Devices.DEVICES, DSL.name("uk_device_user"), new TableField[] { Devices.DEVICES.DEVICE_FINGERPRINT, Devices.DEVICES.USER_ID }, true);
    public static final UniqueKey<PaymentsRecord> PAYMENTS_PKEY = Internal.createUniqueKey(Payments.PAYMENTS, DSL.name("payments_pkey"), new TableField[] { Payments.PAYMENTS.ID }, true);
    public static final UniqueKey<RefreshTokensRecord> REFRESH_TOKENS_PKEY = Internal.createUniqueKey(RefreshTokens.REFRESH_TOKENS, DSL.name("refresh_tokens_pkey"), new TableField[] { RefreshTokens.REFRESH_TOKENS.ID }, true);
    public static final UniqueKey<RefreshTokensRecord> REFRESH_TOKENS_TOKEN_KEY = Internal.createUniqueKey(RefreshTokens.REFRESH_TOKENS, DSL.name("refresh_tokens_token_key"), new TableField[] { RefreshTokens.REFRESH_TOKENS.TOKEN }, true);
    public static final UniqueKey<RefreshTokensRecord> UK_USER_DEVICE = Internal.createUniqueKey(RefreshTokens.REFRESH_TOKENS, DSL.name("uk_user_device"), new TableField[] { RefreshTokens.REFRESH_TOKENS.USER_ID, RefreshTokens.REFRESH_TOKENS.DEVICE_ID }, true);
    public static final UniqueKey<RoutesRecord> ROUTES_PKEY = Internal.createUniqueKey(Routes.ROUTES, DSL.name("routes_pkey"), new TableField[] { Routes.ROUTES.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookingsRecord, UsersRecord> BOOKINGS__FKEYOG2OIC85XG7HSU2JE2LX3S6 = Internal.createForeignKey(Bookings.BOOKINGS, DSL.name("fkeyog2oic85xg7hsu2je2lx3s6"), new TableField[] { Bookings.BOOKINGS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BookingsRecord, RoutesRecord> BOOKINGS__FKP9LLKFDW32YG750N7EG2N01RP = Internal.createForeignKey(Bookings.BOOKINGS, DSL.name("fkp9llkfdw32yg750n7eg2n01rp"), new TableField[] { Bookings.BOOKINGS.ROUTE_ID }, Keys.ROUTES_PKEY, new TableField[] { Routes.ROUTES.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DevicesRecord, UsersRecord> DEVICES__FKRFBRI1YMRWYWDYDC4DGYWE1BT = Internal.createForeignKey(Devices.DEVICES, DSL.name("fkrfbri1ymrwywdydc4dgywe1bt"), new TableField[] { Devices.DEVICES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PaymentsRecord, BookingsRecord> PAYMENTS__FKC52O2B1JKXTTNGUFQP3T7JR3H = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fkc52o2b1jkxttngufqp3t7jr3h"), new TableField[] { Payments.PAYMENTS.BOOKING_ID }, Keys.BOOKINGS_PKEY, new TableField[] { Bookings.BOOKINGS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<PaymentsRecord, UsersRecord> PAYMENTS__FKJ94HGY9V5FW1MUNB90TAR2EJE = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fkj94hgy9v5fw1munb90tar2eje"), new TableField[] { Payments.PAYMENTS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RefreshTokensRecord, UsersRecord> REFRESH_TOKENS__FK1LIH5Y2NPSF8U5O3VHDB9Y0OS = Internal.createForeignKey(RefreshTokens.REFRESH_TOKENS, DSL.name("fk1lih5y2npsf8u5o3vhdb9y0os"), new TableField[] { RefreshTokens.REFRESH_TOKENS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RefreshTokensRecord, DevicesRecord> REFRESH_TOKENS__FKA3BXDJ3AQ8Y05GPIDWQAHRX97 = Internal.createForeignKey(RefreshTokens.REFRESH_TOKENS, DSL.name("fka3bxdj3aq8y05gpidwqahrx97"), new TableField[] { RefreshTokens.REFRESH_TOKENS.DEVICE_ID }, Keys.DEVICES_PKEY, new TableField[] { Devices.DEVICES.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
