/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq;


import com.example.transport_marketplace.jooq.tables.Bookings;
import com.example.transport_marketplace.jooq.tables.Devices;
import com.example.transport_marketplace.jooq.tables.Payments;
import com.example.transport_marketplace.jooq.tables.RefreshTokens;
import com.example.transport_marketplace.jooq.tables.Routes;
import com.example.transport_marketplace.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bookings</code>.
     */
    public final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>public.devices</code>.
     */
    public final Devices DEVICES = Devices.DEVICES;

    /**
     * The table <code>public.payments</code>.
     */
    public final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.routes</code>.
     */
    public final Routes ROUTES = Routes.ROUTES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bookings.BOOKINGS,
            Devices.DEVICES,
            Payments.PAYMENTS,
            RefreshTokens.REFRESH_TOKENS,
            Routes.ROUTES,
            Users.USERS
        );
    }
}
