/*
 * This file is generated by jOOQ.
 */
package com.example.transport_marketplace.jooq;


import com.example.transport_marketplace.jooq.tables.Bookings;
import com.example.transport_marketplace.jooq.tables.Devices;
import com.example.transport_marketplace.jooq.tables.Payments;
import com.example.transport_marketplace.jooq.tables.RefreshTokens;
import com.example.transport_marketplace.jooq.tables.Routes;
import com.example.transport_marketplace.jooq.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.bookings</code>.
     */
    public static final Bookings BOOKINGS = Bookings.BOOKINGS;

    /**
     * The table <code>public.devices</code>.
     */
    public static final Devices DEVICES = Devices.DEVICES;

    /**
     * The table <code>public.payments</code>.
     */
    public static final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public static final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.routes</code>.
     */
    public static final Routes ROUTES = Routes.ROUTES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
