name: Deploy
on: [push]
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - run: mvn clean package -DskipTests
      - uses: appleboy/scp-action@v0.1.6
        with:
          source: "target/*.jar"
          target: "/opt/app"