name: k6 Load Test
on: [push, pull_request]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build app
        run: |
          cd ./backend
          docker compose up -d

      - name: Verify server
        run: |
          docker ps -a
          docker compose exec backend-app curl -s http://localhost:8080/api/health
          docker compose exec redis redis-cli ping

      - name: Run k6 tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/load-test-github.js
          flags: --verbose --http-debug=full
