name: k6 Load Test
on: [push, pull_request]

jobs:
  load-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          ./mvnw clean package -DskipTests
          
      - name: Verify Redis
        run: docker exec $(docker ps -q -f name=redis) redis-cli ping | grep PONG

      - name: Start app
        run: | 
          java -jar target/*.jar &
          sleep 15
          
      - name: Run k6 tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/load-test-github.js