name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: './backend'
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          ditribution: temurin

      - name: Build and start
        run: |
          mvn clean package -DskipTests -P dev &&
          mvn spring-boot:run
          sleep 20
      - name: Check server health
        run: |
          until curl -s -s http://localhost:8080/api/health; do
            sleep 1
          done

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "43572409-0303a959-1afa-478b-84e3-0f692ee527a1"