name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: './backend'
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          ./mvnw clean package -DskipTests -P dev 
          
      - name: Start 
        run: | 
          java -jar target/*.jar &
          sleep 15
          
      - name: Check server health
        run: |
          until curl -s -s http://localhost:8080/api/health; do
            sleep 1
          done

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "43572409-4992a297-2320-4638-960c-d7513cfb6320"